# Generated by Django 4.2.2 on 2023-09-20 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designcrafter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crafter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('crafter_name', models.CharField(max_length=100, null=True)),
                ('crafter_email', models.EmailField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'crafter_data',
            },
        ),
        migrations.CreateModel(
            name='dc_category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=150, null=True)),
                ('cat_image', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disable', 'Disabled')], default='pending', max_length=10)),
            ],
            options={
                'db_table': 'dc_category',
            },
        ),
        migrations.CreateModel(
            name='designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('designer_name', models.CharField(max_length=100, null=True)),
                ('designer_email', models.EmailField(max_length=150, null=True)),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('pending', 'Pending')], default='pending', max_length=10)),
            ],
            options={
                'db_table': 'designer_data',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('user_email', models.EmailField(max_length=150, null=True)),
                ('user_mobile', models.CharField(max_length=15, null=True)),
                ('user_otp', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable')], default='enabled', max_length=10)),
            ],
            options={
                'db_table': 'dc_user_data',
            },
        ),
        migrations.CreateModel(
            name='visits',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(max_length=11, null=True)),
                ('status', models.CharField(choices=[('design', 'Design'), ('category', 'Category')], default='empty', max_length=10)),
                ('visit_date', models.DateTimeField(max_length=100, null=True)),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designcrafter.user')),
            ],
            options={
                'db_table': 'dc_visits',
            },
        ),
        migrations.CreateModel(
            name='dc_designs',
            fields=[
                ('design_size_id', models.AutoField(primary_key=True, serialize=False)),
                ('design_title', models.CharField(max_length=100, null=True)),
                ('design_thumb', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disable', 'Disabled')], default='pending', max_length=10)),
                ('design_discount', models.CharField(max_length=100, null=True)),
                ('design_size_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designcrafter.dc_category')),
            ],
            options={
                'db_table': 'dc_designs',
            },
        ),
        migrations.CreateModel(
            name='dc_design_size',
            fields=[
                ('design_size_id', models.AutoField(primary_key=True, serialize=False)),
                ('design_img', models.CharField(max_length=100, null=True)),
                ('design_size', models.CharField(max_length=100, null=True)),
                ('design_price', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disable', 'Disabled')], default='pending', max_length=10)),
                ('design_size_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designcrafter.dc_designs')),
            ],
            options={
                'db_table': 'dc_design_size',
            },
        ),
    ]
