# Generated by Django 4.2.2 on 2023-09-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designcrafter', '0003_auto_20230920_1106'),
    ]

    operations = [
    ]
