# Generated by Django 4.2.2 on 2023-10-05 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designcrafter', '0005_alter_visits_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, null=True)),
                ('user_email', models.EmailField(max_length=150, null=True)),
                ('user_mobile', models.CharField(max_length=15, null=True)),
                ('user_otp', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable')], default='enabled', max_length=10)),
            ],
            options={
                'db_table': 'dc_user_data',
            },
        ),
        migrations.AlterField(
            model_name='visits',
            name='user_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designcrafter.newuser'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
