# Generated by Django 4.2.2 on 2023-10-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designcrafter', '0006_newuser_alter_visits_user_id_fk_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='password',
        ),
    ]
